import type { Patient } from "./types";

export const mockPatients: Patient[] = [
  {
    id: 1,
    name: "Ardit Krasniqi",
    birthDate: "1990-05-10",
    visitDate: "2025-09-01",
    symptoms: "Dhimbje akute dhëmbi",
    prescription: "Ibuprofen 400mg, 3x në ditë pas ushqimit",
  },
  {
    id: 2,
    name: "Elira Gashi",
    birthDate: "1985-08-21",
    visitDate: "2025-09-01",
    symptoms: "Inflamacion gingival",
    prescription: "Paracetamol 500mg, çdo 6 orë sipas nevojës",
  },
  {
    id: 3,
    name: "Blerim Hoti",
    birthDate: "1975-11-03",
    visitDate: "2025-09-03",
    symptoms: "Infeksion pas ekstraksionit",
    prescription: "Amoxicillin 500mg, 3x në ditë për 7 ditë",
    recoveryDays: 5,
  },
  {
    id: 4,
    name: "Arta Selimi",
    birthDate: "1992-02-15",
    visitDate: "2025-09-03",
    symptoms: "Karies i avancuar",
    prescription: "Ibuprofen 400mg dhe shpëlarje me klorheksidinë",
  },
  {
    id: 5,
    name: "Teuta Berisha",
    birthDate: "1995-12-11",
    visitDate: "2025-09-03",
    symptoms: "Absces dentar",
    prescription: "Augmentin 875/125mg, 2x në ditë",
    recoveryDays: 7,
  },
  {
    id: 6,
    name: "Arjan Leka",
    birthDate: "1988-07-20",
    visitDate: "2025-09-05",
    symptoms: "Dhimbje pas kurorës së dhëmbit",
    prescription: "Ibuprofen 400mg 3x në ditë",
  },
  {
    id: 7,
    name: "Elona Daka",
    birthDate: "1991-03-12",
    visitDate: "2025-09-05",
    symptoms: "Inflamacion i mishit të dhëmbëve",
    prescription: "Paracetamol 500mg dhe shpëlarje me klorheksidinë",
  },
  {
    id: 8,
    name: "Bekim Morina",
    birthDate: "1979-10-05",
    visitDate: "2025-09-06",
    symptoms: "Dhimbje kronike pas mbushjes së dhëmbit",
    prescription: "Ibuprofen 600mg, 2x në ditë",
    recoveryDays: 3,
  },
  {
    id: 9,
    name: "Fjolla Gjinaj",
    birthDate: "1994-06-18",
    visitDate: "2025-09-06",
    symptoms: "Inflamacion i lehtë i gingivës",
    prescription: "Paracetamol 500mg sipas nevojës",
  },
  {
    id: 10,
    name: "Ilir Bajrami",
    birthDate: "1982-01-22",
    visitDate: "2025-09-07",
    symptoms: "Dhimbje pas ekstraksionit të dhëmbit të mençurisë",
    prescription: "Amoxicillin 500mg, 3x në ditë për 5 ditë",
    recoveryDays: 5,
  },
];
